config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  get 'compare_products/index'
  get '/compare_products/compare'
  get 'specifications/index'
  get 'specifications/show'
  get 'categories/index'
  get 'categories/show'
  get '/categories/index', to: 'categories#index'
  get '/categories/:category_id/subcategories', to: 'categories#subcategories', as: 'subcategories'

  resources :article_categories, only: [:index, :show]
  resources :articles, only: [:index, :show]
  
  devise_scope :user do
    get 'users/sessions/sign_out'
    get 'users/cancel_account', to: 'devise/registrations#cancel_account', as: 'cancel_account'
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
  }


  # Defines the root path route ("/")
  # root "articles#index"
  resources :products do
    collection do
      get :all_products
    end

    resources :comments
    member do
      post :favorite, to: 'favorites#create'
      delete :unfavorite, to: 'favorites#destroy'

      get 'where_to_buy', to: 'shopkeeper_shops#where_to_buy'
    end
  end

  resources :favorites, only: [:index]

  # Restricted access for shopkeeper profiles
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :shopkeepers do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  end

  resources :shopkeeper_shops do
    get 'search_product', on: :member
    post 'add_to_shop', on: :member
    post 'remove_to_shop', on: :member
    get 'user_shops', on: :member
    post 'rate', on: :member
  end
  # Root path redirection based on role
  authenticated :user do
    root to: 'users/dashboard#index', as: :authenticated_user_root
  end

  authenticated :shopkeeper do
    root to: 'shopkeepers/dashboard#index', as: :authenticated_shopkeeper_root
  end

  unauthenticated do
    root to: 'landings#index', as: :unauthenticated_root
  end
end

app/models/shopkeeper_shop.rb
class ShopkeeperShop < ApplicationRecord
  belongs_to :user
  has_many :shop_products
  has_many :products, through: :shop_products
  has_many :activities, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :shop_name, :description, :address, :contact_info, presence: true

  def product_count
    products.count
  end

  def log_activity(action, details)
    activities.create(action: action, details: details, created_at: Time.current)
  end

  def average_rating
    ratings.average(:rating).to_f
  end
end

app/controllers/shopkeeper_shops_controller.rb
class ShopkeeperShopsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_shopkeeper!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_shopkeeper_shop, only: [:show, :edit, :update, :destroy]
  before_action :ensure_profile_ownership, only: [:edit, :update, :destroy, :show]

  def index
    if current_user.shopkeeper?
      @shopkeeper_shops = current_user.shopkeeper_shops
    else
      redirect_to users_dashboard_path, alert: 'Access Denied'
    end
  end

  def show
    @product_count = @shopkeeper_shop.product_count
    @shop_products = @shopkeeper_shop.products.page(params[:page]).per(8)

    @categories = Category.all
    @active_category = params[:category_id] || 'all'

    @products_by_category = @categories.each_with_object({}) do |category, hash|
      hash[category.id] = @shop_products.where(category_id: category.id)
    end

    @all_products = @shop_products

    @recent_activities = @shopkeeper_shop.activities.order(created_at: :desc).page(params[:activity_page]).per(5)
  end

  def new
    @shopkeeper_shop = current_user.shopkeeper_shops.new
  end

  def create
    @shopkeeper_shop = current_user.shopkeeper_shops.new(shopkeeper_shop_params)
    if @shopkeeper_shop.save
      @shopkeeper_shop.log_activity('Shop Created', 'Your shop was successfully created.')
      redirect_to @shopkeeper_shop, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shopkeeper_shop.update(shopkeeper_shop_params)
       @shopkeeper_shop.log_activity('Shop Updated', 'Your shop details were successfully updated.')
      redirect_to @shopkeeper_shop, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def search_product
    @products = if params[:search].present?
                  Product.where('name ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(5)
                else
                  redirect_to shopkeeper_profile_path(@shopkeeper_shop)
                end
    @added_product_ids = ShopProduct.where(shopkeeper_shop_id: params[:id]).pluck(:product_id)
  end

  def add_to_shop
    product = Product.friendly.find(params[:product_id])
    @shop = ShopkeeperShop.find(params[:shop_id])
    search_params = params[:search] || {}
    quantity = params[:quantity].to_i

    if @shop.products.include?(product)
      flash[:alert] = "Product is already in your shop."
    else
      shop_product = ShopProduct.new(product_id: product.id, shopkeeper_shop_id: @shop.id, quantity: quantity)
      if shop_product.save
        @shop.log_activity('Product Added', "Product '#{product.name}' (Quantity: #{quantity}) was added to your shop.")
        flash[:notice] = "#{product.name} added to your shop successfully."
      else
        flash[:alert] = "Failed to add product to your shop."
      end
    end

    respond_to do |format|
      format.html { redirect_to search_product_shopkeeper_shop_path(@shop, search: search_params) }
      format.js
    end
  end

  def remove_to_shop
    shop_product = ShopProduct.where(product_id: params[:product_id], shopkeeper_shop_id: params[:shop_id]).first
    @shop = ShopkeeperShop.find(params[:shop_id])
    product = Product.find(params[:product_id])
    search_params = params[:search] || {}

    if shop_product.destroy
      @shop.log_activity('Product Removed', "Product '#{product.name}'")
      flash[:notice] = "#{product.name} removed to your shop successfully."
    else
      flash[:alert] = "Failed to add product to your shop."
    end

    respond_to do |format|
      format.html { redirect_to search_product_shopkeeper_shop_path(@shop, search: search_params) }
      format.js
    end
  end

  def destroy
    @shopkeeper_shop.destroy
    redirect_to shopkeepers_dashboard_path, alert: 'Shop was successfully destroyed.'
  end

  def user_shops
    @shopkeeper_shop = ShopkeeperShop.find(params[:id])
    @shop_products = @shopkeeper_shop.products.page(params[:page]).per(8)

    @categories = Category.all
    @products_by_category = @categories.each_with_object({}) do |category, hash|
      products = @shop_products.where(category_id: category.id)
      hash[category.id] = products if products.any?
    end

    @all_products = @shop_products

    @active_category = params[:category] || 'all'

    # Fetch or initialize the rating for the current user
    @rating = Rating.find_or_initialize_by(user: current_user, shopkeeper_shop: @shopkeeper_shop)
  end

  def rate
    @shopkeeper_shop = ShopkeeperShop.find(params[:id])
    @rating = Rating.find_or_initialize_by(user: current_user, shopkeeper_shop: @shopkeeper_shop)
    @rating.rating = params[:rating].to_i

    if @rating.save
      # Calculate the new average rating for the shop
      average_rating = @shopkeeper_shop.ratings.average(:rating).to_f.round(2)

      # Respond with JSON for AJAX
      render json: { average_rating: average_rating, rating: @rating.rating }
    else
      render json: { error: 'Unable to save rating' }, status: :unprocessable_entity
    end
  end

  def where_to_buy
    @product = Product.friendly.find(params[:id])
    @shop_products = ShopProduct.where(product_id: @product.id).includes(:shopkeeper_shop)
  end

  private

  def set_shopkeeper_shop
    @shopkeeper_shop = ShopkeeperShop.find(params[:id])
  end

  def shopkeeper_shop_params
    params.require(:shopkeeper_shop).permit(:shop_name, :description, :address, :contact_info, :operating_hours, :location, :shop_images)
  end

  def authorize_shopkeeper!
    redirect_to root_path, alert: 'Access Denied' unless current_user.shopkeeper?
  end

  def ensure_profile_ownership
    redirect_to root_path, alert: 'Access Denied' unless @shopkeeper_shop.user == current_user || !current_user.shopkeeper?
  end
end

app/helpers/shopkeeper_shops_helper.rb
module ShopkeeperShopsHelper
end

app/views/shopkeeper_shops/_products_list.html.erb
<% if products.any? %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <!-- Card -->
        <div class="card card-hover">
          <% if product.main_image.present? %>
            <a href="<%= product_path(product) %>">
              <%= image_tag url_for(product.main_image), class: "card-img-top", style: "object-fit: cover; width: 100%; height: auto;" %>
            </a>
          <% else %>
            <a href="<%= product_path(product) %>">
              <img src="/assets/official.png" alt="product image" class="card-img-top" style="object-fit: cover; width: 100%; height: auto;">
            </a>
          <% end %>
          <!-- Card Body -->
          <div class="landing-card-body">
            <h4 class="mb-2 text-truncate">
              <a href="<%= product_path(product) %>" class="text-inherit"><%= product.name %></a>
            </h4>
            <p>Quantity: <%= shop_product_quantity(@shopkeeper_shop, product) %></p>
            <div class="lh-1">
              <span class="text-dark fw-bold">RS <%= product.price %></span>
              <del class="fs-6 text-muted">RS <%= product.actual_price %></del>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="col-12">
    <div class="alert alert-info text-center">
      <h5 class="alert-heading">No Products Available!</h5>
      <p>It looks like there are no products in this category. Please check back later or contact support for assistance.</p>
      <p>For immediate assistance, you can</p>
      <div class="text-center mt-4">
        <a href="https://wa.me/923134209115" target="_blank" class="btn btn-success rounded-pill px-4 py-2 text-white" style="background-color: #25D366; border-color: #25D366; font-weight: 600;">
            Contact Us on WhatsApp
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/shopkeeper_shops/_shopkeeper_products_list.html.erb
<% if products.any? %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <!-- Card -->
        <div class="card card-hover">
          <% if product.main_image.present? %>
            <a href="<%= product_path(product) %>">
              <%= image_tag url_for(product.main_image), class: "card-img-top", style: "object-fit: cover; width: 100%; height: auto;" %>
            </a>
          <% else %>
            <a href="<%= product_path(product) %>">
              <img src="/assets/official.png" alt="product image" class="card-img-top" style="object-fit: cover; width: 100%; height: auto;">
            </a>
          <% end %>
          <!-- Card Body -->
          <div class="landing-card-body">
            <h4 class="mb-2 text-truncate text-truncate-line-2">
              <a href="<%= product_path(product) %>" class="text-inherit card-img-top inner-img">
                <div class="product-name">
                  <span class="name-part name-part-1"><%= product.name.split(' ').first %></span>
                  <span class="name-part name-part-2"><%= product.name.split(' ')[1..-1].join(' ') %></span>
                </div>
              </a>
            </h4>
            <p>Quantity: <%= shop_product_quantity(@shopkeeper_shop, product) %></p>
            <div class="lh-1">
              <span class="text-dark fw-bold">RS <%= product.price %></span>
              <% if product.actual_price.present? %>
                <del class="fs-6 text-muted">RS <%= product.actual_price %></del>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="col-12">
    <div class="alert alert-info text-center">
      <h5 class="alert-heading">No Products Available!</h5>
      <p>It looks like there are no products in this category. Please check back later or contact support for assistance.</p>
      <p>For immediate assistance, you can</p>
      <div class="text-center mt-4">
        <a href="https://wa.me/923134209115" target="_blank" class="btn btn-success rounded-pill px-4 py-2 text-white" style="background-color: #25D366; border-color: #25D366; font-weight: 600;">
            Contact Us on WhatsApp
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/shopkeeper_shops/_user_product_list.html.erb
<div class="row">
  <% if products.any? %>
    <% products.each do |product| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <!-- Card -->
        <div class="card card-hover">
          <% if product&.main_image.present? %>
            <a href="<%= product_path(product) %>">
              <%= image_tag url_for(product.main_image), class: "card-img-top", style: "object-fit: cover; width: 100%; height: auto;" %>
            </a>
          <% else %>
            <a href="<%= product_path(product) %>">
              <img src="/assets/official.png" alt="product image" class="card-img-top" style="object-fit: cover; width: 100%; height: auto;">
            </a>
          <% end %>
          <!-- Card Body -->
          <div class="landing-card-body">
            <h4 class="mb-2 text-truncate">
              <a href="<%= product_path(product) %>" class="text-inherit"><%= product.name %></a>
            </h4>
            <p>Quantity: <%= shop_product_quantity(@shopkeeper_shop, product) %></p>
            <div class="lh-1">
              <span class="text-dark fw-bold">RS <%= product.price %></span>
              <del class="fs-6 text-muted">RS <%= product.actual_price %></del>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-12">
      <div class="alert alert-info text-center">
        <h5 class="alert-heading">No Products Found!</h5>
        <p>It looks like there are no products available in this category at the moment. Please check back later or contact us for more information!</p>
        <p>For immediate assistance, you can</p>
        <div class="text-center mt-4">
          <a href="https://wa.me/923134209115" target="_blank" class="btn btn-success rounded-pill px-4 py-2 text-white" style="background-color: #25D366; border-color: #25D366; font-weight: 600;">
              Contact Us on WhatsApp
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shopkeeper_shops/add_to_shop.js.erb
var productId = "<%= @product.id %>";
var productDiv = $("#product-" + productId);

if (productDiv.length > 0) {
  productDiv.find("button").replaceWith('<button type="button" disabled>Added</button>');
}

app/views/shopkeeper_shops/search_product.html.erb
<body>
  <div id="db-wrapper">
    <!-- Sidebar -->
    <%= render 'shopkeepers/shopkeeper_sidebar' %>
    <main id="page-content">
      <div class="header">
        <!-- navbar -->
        <%= render 'shopkeepers/shopkeeper_navbar' %>
      </div>
      <section class="container-fluid p-4">
        <div class="row">
          <!-- Page header -->
          <div class="col-lg-12 col-md-12 col-12">
            <%= render 'shared/flash_messages' %>
            <div class="border-bottom pb-3 mb-3">
              <div class="mb-2 mb-lg-0">
                <h1 class="mb-0 h2 fw-bold">Add Phones to Shop</h1>
                <!-- Breadcrumb -->
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                      <a href="<%= shopkeepers_dashboard_path %>">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                      <a href="<%= shopkeeper_shop_path %>">Shop</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                      Add to Shop
                    </li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>

        <!-- row -->
        <div class="row">
          <div class="col-lg-8">
            <!-- card -->
            <div class="card">
              <!-- card header -->
              <div class="card-header">
                <div class="d-flex">
                  <!-- heading -->
                  <h4 class="mb-0">Available Products</h4>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive table-card">
                  <!-- Table -->
                  <table class="table mb-0 text-nowrap">
                    <!-- Table Head -->
                    <thead class="table-light">
                      <tr class="text-center">
                        <th>Photo</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% if @products.any? %>
                        <% @products.each do |product| %>
                          <tr class="align-middle">
                            <td class="text-center">
                              <div class="d-flex justify-content-center align-items-center">
                                <a href="<%= product_path(product) %>">
                                  <img src="/assets/official.png" alt="" class="img-4by3-md rounded">
                                </a>
                              </div>
                            </td>
                            <td class="text-center">
                              <a href="<%= product_path(product) %>">
                                <h4 class="mb-0"><%= product.name %></h4>
                              </a>
                            </td>
                            <td class="text-center">
                              <h4 class="mb-0"><%= product.price %></h4>
                            </td>
                            <% if @added_product_ids.include?(product.id) %>
                              <%= form_with url: remove_to_shop_shopkeeper_shop_path(product_id: product.id, user_id: current_user.id, shop_id: params[:id], search: params[:search]), method: :post, remote: true do %>
                                <td class="text-center">
                                  <h4 class="mb-0"></h4>
                                </td>
                                <td class="text-center">
                                  <!-- Add to Shop Button -->
                                  <%= submit_tag 'Remove to Shop', class: 'btn btn-danger' %>
                                </td>
                              <% end %>
                            <% else %>
                              <%= form_with url: add_to_shop_shopkeeper_shop_path(product_id: product.id, user_id: current_user.id, shop_id: params[:id], search: params[:search]), method: :post, remote: true do %>
                                <td class="text-center">
                                  <!-- Quantity Input Design -->
                                  <div class="input-group flex-nowrap justify-content-center">
                                    <input type="button" value="-" class="button-minus form-control text-center flex-xl-none w-xl-30 w-xxl-10 px-0 py-1" data-field="quantity">
                                    <%= number_field_tag :quantity, 1, step: 1, min: 1, class: "quantity-field form-control text-center flex-xl-none w-xl-30 w-xxl-10 px-0 py-1" %>
                                    <input type="button" value="+" class="button-plus form-control text-center flex-xl-none w-xl-30 w-xxl-10 px-0 py-1" data-field="quantity">
                                  </div>
                                </td>
                                <td class="text-center">
                                  <!-- Add to Shop Button -->
                                  <%= submit_tag 'Add to Shop', class: 'btn btn-primary' %>
                                </td>
                              <% end %>
                            <% end %>
                          </tr>
                        <% end %>
                      <% else %>
                        <tr>
                          <td colspan="5" class="text-center">No products available.</td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- Pagination Links -->
            <div class="mt-4 d-flex justify-content-center">
              <%= paginate @products %>
            </div>
            <%# <div class="mt-4 d-flex justify-content-between">
              <a href="product-grid.html" class="btn btn-outline-primary">Continue Shopping</a>
              <a href="checkout.html" class="btn btn-primary">Checkout</a>
            </div> %>
          </div>
        </div>
      </section>
    </main>
  </div>
</body>

app/views/shopkeeper_shops/user_shops.erb
<body>
    <main>
      <div class="container-fluid">
        <%= render 'devise/registrations/user_info' %>
      </div>
      <!-- Container fluid -->
      <section class="container-fluid p-4">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-12 mb-2">
            <!-- Page header -->
            <div class="d-lg-flex align-items-center justify-content-between">
              <div class="mb-2 mb-lg-0">
                <h1 class="mb-0 h2 fw-bold"><%= @shopkeeper_shop.shop_name %>
                </h1>
              </div>
            </div>
          </div>
        </div>
        <!-- row  -->
        <div class="row">
          <div class="col-12 mb-4">
            <!-- nav  -->
            <ul class="nav nav-lb-tab">
              <li class="nav-item ms-0 me-3">
                <a class="nav-link active" href="#">Overview</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="row">

          <div class="col-md-12 col-xl-8 col-12">
            <div class="row">
              <div class="col-12 mb-4">
                <div class="card">
                  <div class="card-header">
                    <div class="d-flex justify-content-between
                     align-items-center">
                      <div>
                        <h4 class="mb-0">Shop Overview</h4>
                      </div>
                      <!-- dropdown  -->
                      <% if current_user.shopkeeper? && can?(:update, @shopkeeper_shop) %>
                        <div>
                          <span class="dropdown dropstart">
                            <a class="btn-icon btn btn-ghost btn-sm rounded-circle" href="#" role="button"
                               id="Dropdown<%= @shopkeeper_shop.id %>" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fe fe-more-vertical"></i>
                            </a>
                            <span class="dropdown-menu" aria-labelledby="Dropdown<%= @shopkeeper_shop.id %>">
                              <span class="dropdown-header">Settings</span>
                              <%= link_to 'Edit Shop', edit_shopkeeper_shop_path(@shopkeeper_shop), class: 'dropdown-item' %>
                              <%= button_to 'Delete Shop', shopkeeper_shop_path(@shopkeeper_shop), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item btn btn-danger' %>
                            </span>
                          </span>
                        </div>
                      <% end %>
                    </div>
                  </div>
                  <div class="card-body">
                    <p><%= @shopkeeper_shop.description %></p>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item px-0">
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="d-flex align-items-center">
                            <i class="bi bi-calendar me-2 text-primary"></i>
                            <div class="ms-2">
                              <h5 class="mb-0 text-body">Start Date</h5>
                            </div>
                          </div>
                          <div>
                            <p class="text-dark mb-0 fw-semibold"><%= @shopkeeper_shop.created_at.strftime("%d %b, %Y") %></p>
                          </div>
                        </div>
                      </li>
                      <li class="list-group-item  px-0">
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="d-flex align-items-center">
                            <i class="bi bi-geo-alt me-2 text-primary"></i>
                            <div class="ms-2">
                              <h5 class="mb-0 text-body">Address</h5>
                            </div>
                          </div>
                          <div>
                            <p class="text-dark mb-0 fw-semibold"><%= @shopkeeper_shop.address %></p>
                          </div>
                        </div>
                      </li>

                      <li class="list-group-item  px-0">
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="d-flex align-items-center">
                            <i class="bi bi-clock me-2 text-primary"></i>
                            <div class="ms-2">
                              <h5 class="mb-0 text-body">Operating Hours</h5>
                            </div>
                          </div>
                          <div>
                            <p class="text-dark mb-0 fw-semibold"><%= @shopkeeper_shop.operating_hours %></p>
                          </div>
                        </div>
                      </li>

                      <li class="list-group-item  px-0">
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="d-flex align-items-center">
                            <i class="bi bi-geo-alt me-2 text-primary"></i>
                            <div class="ms-2">
                              <h5 class="mb-0 text-body">Location</h5>
                            </div>
                          </div>
                          <div>
                            <p class="text-dark mb-0 fw-semibold"><%= @shopkeeper_shop.location %></p>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-12 mb-4">
                <!-- card -->
                <div class="card">
                  <!-- card header -->
                  <div class="card-header">
                    <h4 class="mb-0">All Phones in This Shop</h4>
                    <div class="d-flex flex-wrap mt-2">
                      <!-- Example button group -->
                      <button class="btn btn-primary me-2 mb-2">Categories</button>
                      <a href="#" class="btn btn-primary me-2 mb-2">All</a>
                      <a href="#" class="btn btn-primary me-2 mb-2">Samsung</a>
                      <a href="#" class="btn btn-primary me-2 mb-2">Oppo</a>
                      <a href="#" class="btn btn-primary me-2 mb-2">Vivo</a>
                      <!-- Add more buttons as needed -->
                    </div>
                  </div>
                  <!-- card body -->
                  <div class="card-body">
                    <!-- This Shop's Phones -->
                    <div class="row">
                      <!-- Iterate over products -->
                      <% @shop_products.each do |product| %>
                        <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                          <!-- Card -->
                          <div class="card card-hover">
                            <% if product&.main_image.present? %>
                              <a href="<%= product_path(product) %>">
                                <%= image_tag url_for(product.main_image), class: "card-img-top", style: "object-fit: cover; width: 100%; height: auto;" %>
                              </a>
                            <% else %>
                              <a href="<%= product_path(product) %>">
                                <img src="/assets/official.png" alt="product image" class="card-img-top" style="object-fit: cover; width: 100%; height: auto;">
                              </a>
                            <% end %>
                            <!-- Card Body -->
                            <div class="landing-card-body">
                              <h4 class="mb-2 text-truncate">
                                <a href="<%= product_path(product) %>" class="text-inherit"><%= product.name %></a>
                              </h4>
                              <!-- Price -->
                              <div class="lh-1">
                                <span class="text-dark fw-bold">RS <%= product&.price %></span>
                                <del class="fs-6 text-muted">RS <%= product&.actual_price %></del>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                      <!-- End of This Shop's Phones -->
                    </div>
                  </div>
                </div>
                <!-- Pagination Links -->
                <div class="mt-4 d-flex justify-content-center">
                  <%= paginate @shop_products %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 col-xl-4 col-12">
            <!-- card  -->
            <div class="card mb-4 bg-primary border-primary">
              <a href="#"  class="card-img-top"> <img src="/assets/category-index.jpg" size="411x222" class="card-img-top rounded-top-md"
                    alt="Article Image"></a>
              <!-- card body  -->
              <div class="card-body">

                <h4 class="card-title text-white">Launch Date </h4>

                <!-- dropdown  -->
                <div class="d-flex justify-content-between align-items-center mt-8">
                  <div>
                    <h1 class="display-4 text-white mb-1"> <%= (Date.current - @shopkeeper_shop.created_at.to_date).to_i %> Days</h1>
                    <p class="mb-0 text-white"><%= Date.today.strftime("%d %B, %A") %></p>
                  </div>
                  <div>
                    <i class="fe fe-flag fs-1 text-light-primary"></i>
                  </div>
                </div>

              </div>

            </div>
            <!-- card  -->
            <div class="card mb-4 ">
              <!-- card body  -->
              <div class="card-body">

                <h4 class=" card-title ">Overall Customer Satisfaction Rating for This Shop</h4>

                <div id="progressChart"></div>

              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  </div>
</body>