config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  get 'compare_products/index'
  get '/compare_products/compare'
  get 'specifications/index'
  get 'specifications/show'
  get 'categories/index'
  get 'categories/show'
  get '/categories/index', to: 'categories#index'
  get '/categories/:category_id/subcategories', to: 'categories#subcategories', as: 'subcategories'

  resources :article_categories, only: [:index, :show]
  resources :articles, only: [:index, :show]
  
  devise_scope :user do
    get 'users/sessions/sign_out'
    get 'users/cancel_account', to: 'devise/registrations#cancel_account', as: 'cancel_account'
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
  }


  # Defines the root path route ("/")
  # root "articles#index"
  resources :products do
    collection do
      get :all_products
    end

    resources :comments
    member do
      post :favorite, to: 'favorites#create'
      delete :unfavorite, to: 'favorites#destroy'

      get 'where_to_buy', to: 'shopkeeper_shops#where_to_buy'
    end
  end

  resources :favorites, only: [:index]

  # Restricted access for shopkeeper profiles
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :shopkeepers do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  end

  resources :shopkeeper_shops do
    get 'search_product', on: :member
    post 'add_to_shop', on: :member
    post 'remove_to_shop', on: :member
    get 'user_shops', on: :member
    post 'rate', on: :member
  end
  # Root path redirection based on role
  authenticated :user do
    root to: 'users/dashboard#index', as: :authenticated_user_root
  end

  authenticated :shopkeeper do
    root to: 'shopkeepers/dashboard#index', as: :authenticated_shopkeeper_root
  end

  unauthenticated do
    root to: 'landings#index', as: :unauthenticated_root
  end
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :keep_images, if: :will_save_change_to_images?
  has_many_attached :images
  belongs_to :article_category
  belongs_to :admin_user, class_name: 'AdminUser'

  validates :title, :content, :article_category_id, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["admin_user", "article_category"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["admin_user_id", "article_category_id", "content", "created_at", "id", "title", "updated_at"]
  end

  def self.ransackable_attributes(auth_object = nil)
    super + ['has_images']  # Add other attributes as needed
  end

  scope :with_images, -> {
    joins(:images_attachments)
    .group('articles.id')
    .having('COUNT(active_storage_attachments.id) > 0')
  }

  # Scope to find articles without images
  scope :without_images, -> {
    left_joins(:images_attachments)
    .group('articles.id')
    .having('COUNT(active_storage_attachments.id) = 0')
  }

  # Method to check if an article has images
  def self.has_images?
    joins(:images_attachments)
    .group('articles.id')
    .having('COUNT(active_storage_attachments.id) > 0')
  end

  private

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.page(params[:page]).per(6)
    @article_categories = ArticleCategory.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<body class="bg-white">
  <!-- Page content -->
  <main>

    <!-- Page header -->
    <section class="py-7 ">
      <div class="container">
        <div class="row ">
          <div class="offset-xl-2 col-xl-8 offset-lg-1 col-lg-10 col-md-12 col-12">
            <div class="text-center mb-5">
              <h1 class=" display-2 fw-bold">All Categories Blogs</h1>
              <p class=" lead">
                Browse through our extensive collection of articles, featuring the latest trends, insights, and expert advice across various topics.
              </p>
            </div>
            <!-- Form -->
            <form class="row px-md-20">
              <div class="mb-3 col ps-3">
                <input type="email" class="form-control" placeholder="Email Address" required="">
              </div>
              <div class="mb-3 col-auto ps-0">
                <button class="btn btn-primary" type="submit">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <!-- Content -->
    <section class="pb-16">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-12">
            <div class="row">
              <% if @articles.any? %>
                <% @articles.each do |article| %>
                  <div class=" col-lg-6 col-md-12 col-12">
                    <!-- Card -->
                    <div class="card mb-4  shadow-lg">
                      <% if article.images.attached? %>
                        <% first_image = article.images.first %>
                          <a href="<%= article_path(article) %>"  class="card-img-top"><%= image_tag url_for(first_image), alt: "Article Image", size: "411x222", class:"card-img-top rounded-top-md" %>
                      <% else %>
                        <a href="<%= article_path(article) %>"  class="card-img-top">
                          <img src="/assets/category-article-img.jpg", class="card-img-top rounded-top-md" alt="blogpost" size= "411x222"></a>
                      <% end %>
                      <!-- Card body-->
                      <div class="card-body">
                        <a href="<%= article_categories_path %>" class="fs-5 fw-semibold d-block mb-3 text-primary">
                          <%= article.article_category.name %>
                        </a>
                        <h3><a href="<%= article_path(article) %>" class="text-inherit">
                            <%= article.title %>
                          </a>
                        </h3>
                        <p><%= truncate(article.content, length: 100) %></p>
                        <!-- Media content -->
                            <!-- Row -->
                        <div class="row align-items-center g-0 mt-4">
                          <div class="col-auto">
                            <img src="/assets/mobilo1.png" alt="avatar" class="rounded-circle avatar-sm me-2">
                          </div>
                          <div class="col lh-1">
                            <h5 class="mb-1">MyMobilo</h5>
                            <p class="fs-6 mb-0"><%= article.created_at.strftime("%B %d, %Y") %></p>
                          </div>
                          <div class="col-auto">
                            <p class="fs-6 mb-0">15 Min Read</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <div class="col-12">
                  <p class="text-center">No articles available at the moment. Please check back later.</p>
                </div>
              <% end %>
                <!-- Pagination -->
                <%= paginate @articles if @articles.present? %>
            </div>
          </div>
          <div class="col-lg-4 col-md-5 col-12 mt-6 mt-md-0">
            <!-- search -->
            <div class="mb-4">
              <div class="mb-3 position-relative">
                <input type="search" class="form-control " placeholder="Search...">
                <span class="position-absolute end-0 top-0 mt-2  me-3 "><i class="bi bi-search fs-5"></i></span>
              </div>
            </div>
            <!-- card -->
            <div class="card mb-4 border ">
              <!-- card body -->
              <div class="card-body p-4">
                <h3>Recent Posts</h3>
                <div class="mt-3">
                  <!-- list -->
                  <ul class="list-unstyled mb-0">
                    <li class="mb-3">
                      <h4 class="lh-lg"><a href="#" class="text-inherit">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></h4>
                    </li>
                    <li class="mb-3">
                      <h4 class="lh-lg"><a href="#" class="text-inherit">
                        Duis placerat mi quis purus feugiat, at bibendum arcu dignissim.</a></h4>
                    </li>
                    <li class="mb-3">
                      <h4 class="lh-lg"><a href="#" class="text-inherit">
                        Morbi sit amet metus nec elit hendrerit luctus.</a></h4>
                    </li>
                    <li>
                      <h4 class="lh-lg"><a href="#" class="text-inherit">
                        Vivamus ac sapien ultricies dolor ullamcorper porttitor.</a></h4>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- card -->
            <div class="card mb-4 border ">
              <!-- card body -->
              <div class="card-body p-4">
                <h3>Categories</h3>
                <div class="mt-3">
                  <!-- list -->
                  <ul class="list-unstyled mb-0 nav nav-x-0 flex-column">
                    <% if @article_categories.any? %>
                      <% @article_categories.each do |category| %>
                        <li class="lh-lg mb-1">
                          <i class="fe fe-arrow-right text-muted"></i>
                          <a href="<%= article_category_path(category) %>" class="text-link d-inline">
                            <%= category.name %></a>
                        </li>
                      <% end %>
                    <% else %>
                      <div class="alert p-4">
                        <h3 class="mb-3">No Categories Yet</h3>
                        <p class="mb-0">
                          It looks like there aren't any categories available at the moment.
                          We're constantly updating our content, so please check back soon for exciting new categories to explore!
                        </p>
                      </div>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
            <!-- card -->
            <div class="card mb-4 border ">
              <!-- card body -->
              <div class="card-body p-4">
                <h3>Archive</h3>
                <div class="mt-3">
                  <!-- list -->
                  <ul class="list-unstyled mb-0 nav nav-x-0 flex-column">
                    <li class="lh-lg mb-1">

                      <i class="fe fe-arrow-right text-muted"></i>
                      <a href="#" class="text-link d-inline">
                        March 2021</a>
                    </li>
                    <li class="lh-lg mb-1">
                      <i class="fe fe-arrow-right text-muted"></i>
                      <a href="#" class="text-link d-inline">
                        February 2021</a>
                    </li>
                    <li class="lh-lg mb-1">
                      <i class="fe fe-arrow-right text-muted"></i>
                      <a href="#" class="text-link d-inline">
                        January 2021</a>
                    </li>
                    <li class="lh-lg mb-1">
                      <i class="fe fe-arrow-right text-muted"></i>
                      <a href="#" class="text-link d-inline">
                        December 2020</a>
                    </li>

                  </ul>
                </div>
              </div>
            </div>
              <!-- card -->
              <div class="card mb-4 border ">
                <!-- card body -->
                <div class="card-body p-4">
                  <h3>Tags</h3>
                  <div class="mt-3">
                    <a href="#" class="btn btn-light btn-xs mb-2">business</a>
                    <a href="#" class="btn btn-light btn-xs  mb-2">e-commerce</a>
                    <a href="#" class="btn btn-light btn-xs  mb-2">course</a>
                    <a href="#" class="btn btn-light btn-xs  mb-2">dashboard</a>
                    <a href="#" class="btn btn-light btn-xs  mb-2">landings</a>
                    <a href="#" class="btn btn-light btn-xs  mb-2">marketing</a>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</body>

app/views/articles/show.html.erb
<body class="bg-white">
  <!-- Page content -->
  <main>
    <!-- Content -->
    <section class="py-7 py-lg-8 pb-14">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-8 col-lg-8 col-md-12 col-12 mb-2">
            <div class="text-center mb-4">
              <a href="<%= article_categories_path %>" class="fs-5 fw-semibold d-block mb-4 text-primary"><%= @article.article_category.name %></a>
              <h1 class="display-3 fw-bold mb-4"><%= @article.title %></h1>
              <span class="mb-3 d-inline-block"><%= @article.created_at.to_s(:long) %></span>
            </div>
            <!-- Media -->
            <div class="d-flex justify-content-between align-items-center mb-5">
              <div class="d-flex align-items-center">
                <img src="/assets/mobilo1.png" alt="avatar" class="rounded-circle avatar-md">
                <div class="ms-2 lh-1">
                  <h5 class="mb-1 ">MyMobilo</h5>
                  <span class="text-primary">Your Gateway to Mobile Innovation</span>
                </div>
              </div>
              <div>
                <span class="ms-2 text-muted">Share</span>
                <a href="#" class="ms-2 text-muted"><i class="mdi mdi-facebook fs-4"></i></a>
                <a href="#" class="ms-2 text-muted"><i class="mdi mdi-twitter fs-4"></i></a>
                <a href="#" class="ms-2 text-muted "><i class="mdi mdi-linkedin fs-4"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="row justify-content-center">
          <!-- Image -->
          <div class="col-xl-10 col-lg-10 col-md-12 col-12 mb-6">
            <% if @article.images.attached? %>
              <% first_image = @article.images.first %>
              <a href="<%= articles_path %>"  class="card-img-top"><%= image_tag url_for(first_image), alt: "Article Image", class:"card-img-top rounded-top-md" %></a>
            <% else %>
              <a href="<%= articles_path %>"  class="card-img-top"> <img src="/assets/Article-show.jpg" class="card-img-top rounded-top-md"
                alt="blogpost"></a>
            <% end %>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-xl-8 col-lg-8 col-md-12 col-12 mb-2">
            <!-- Descriptions -->
            <div>
              <div class="mb-4">
                <p class="lead text-dark">
                  <%= @article.title %>
                </p>
                <p>
                  <%= @article.content.html_safe %>
                </p>
              </div>
              <%= link_to 'Back to Articles', articles_path, class: 'btn btn-secondary' %>
            </div>

            <!-- Media -->
            <hr class="mt-8 mb-5">
            <div class="d-flex justify-content-between align-items-center mb-5">
              <div class="d-flex align-items-center">
                <img src="/assets/mobilo1.png" alt="avatar" class="rounded-circle avatar-md">
                <div class="ms-2 lh-1">
                  <h5 class="mb-1 ">MyMobilo</h5>
                  <span class="text-primary">Your Gateway to Mobile Innovation</span>
                </div>
              </div>
              <div>
                <span class="ms-2 text-muted">Share</span>
                <a href="#" class="ms-2 text-muted"><i class="mdi mdi-facebook fs-4"></i></a>
                <a href="#" class="ms-2 text-muted"><i class="mdi mdi-twitter fs-4"></i></a>
                <a href="#" class="ms-2 text-muted "><i class="mdi mdi-linkedin fs-4"></i></a>
              </div>
            </div>
            <!-- Subscribe to Newsletter -->
            <div class="py-lg-12 py-6">
              <div class="text-center mb-6">
                <h2 class="display-4 fw-bold">Sign up for our Newsletter</h2>
                <p class="mb-0 lead">Join our newsletter and get resources, curated content, and design inspiration
                  delivered straight to your inbox.</p>
              </div>
              <!-- Form -->
              <form class="row px-md-20">
                <div class="mb-3 col ps-0 ms-2 ms-md-0">
                  <input type="email" class="form-control" placeholder="Email Address" required>
                </div>
                <div class="mb-3 col-auto ps-0">
                  <button class="btn btn-primary" type="submit">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- Container -->
      <div class="container">
        <div class="row">
          <div class="col-xl-12 col-lg-12 col-md-12 col-12">
            <div class="my-5">
              <h2>Related Post</h2>
            </div>
          </div>
          <div class="col-xl-4 col-lg-4 col-md-6 col-12">
            <!-- Card -->
            <div class="card mb-4 shadow-lg ">
              <a href="#" class="card-img-top"> <img src="/assets/category-article-img.jpg"
                  class="card-img-top rounded-top-md" alt="blogpost"></a>
              <!-- Card body -->
              <div class="card-body">
                <a href="#" class="fs-5 fw-semibold d-block mb-3 text-primary">Workshop</a>
                <a href="blog-single.html">
                  <h3>The Best DevOps Tools for Your Application Lifecycle</h3>
                </a>
                <p>Inventore pariatur veritatis maxime fugiat sint dolorem officiis nemo quis!
                </p>
                <!-- Media content -->
                <div class="row align-items-center g-0 mt-4">
                  <div class="col-auto">
                    <img src="/assets/mobilo1.png" alt="avatar" class="rounded-circle avatar-sm me-2">
                  </div>
                  <div class="col lh-1">
                    <h5 class="mb-1">Dustin Warren</h5>
                    <p class="fs-6 mb-0">September 09, 2020</p>
                  </div>
                  <div class="col-auto">
                    <p class="fs-6 mb-0">12 Min Read</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</body>