config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  get 'compare_products/index'
  get '/compare_products/compare'
  get 'specifications/index'
  get 'specifications/show'
  get 'categories/index'
  get 'categories/show'
  get '/categories/index', to: 'categories#index'
  get '/categories/:category_id/subcategories', to: 'categories#subcategories', as: 'subcategories'

  resources :article_categories, only: [:index, :show]
  resources :articles, only: [:index, :show]
  
  devise_scope :user do
    get 'users/sessions/sign_out'
    get 'users/cancel_account', to: 'devise/registrations#cancel_account', as: 'cancel_account'
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
  }


  # Defines the root path route ("/")
  # root "articles#index"
  resources :products do
    collection do
      get :all_products
    end

    resources :comments
    member do
      post :favorite, to: 'favorites#create'
      delete :unfavorite, to: 'favorites#destroy'

      get 'where_to_buy', to: 'shopkeeper_shops#where_to_buy'
    end
  end

  resources :favorites, only: [:index]

  # Restricted access for shopkeeper profiles
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :shopkeepers do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  end

  resources :shopkeeper_shops do
    get 'search_product', on: :member
    post 'add_to_shop', on: :member
    post 'remove_to_shop', on: :member
    get 'user_shops', on: :member
    post 'rate', on: :member
  end
  # Root path redirection based on role
  authenticated :user do
    root to: 'users/dashboard#index', as: :authenticated_user_root
  end

  authenticated :shopkeeper do
    root to: 'shopkeepers/dashboard#index', as: :authenticated_shopkeeper_root
  end

  unauthenticated do
    root to: 'landings#index', as: :unauthenticated_root
  end
end

app/controllers/shopkeepers/dashboard_controller.rb
class Shopkeepers::DashboardController < ApplicationController
  before_action :authenticate_shopkeeper!

  def index
    if current_user.shopkeeper?
      # Fetch only the current user's shop profiles
      @shopkeeper_shops = current_user.shopkeeper_shops
    else
      # Fetch all shop profiles for users
      @shopkeeper_shops = ShopkeeperShop.all
    end

    # Optionally filter based on search if a search term is provided
    if params[:search].present?
      @shopkeeper_shops = @shopkeeper_shops.where('shop_name ILIKE ?', "%#{params[:search]}%")
    end
  end

  def authenticate_shopkeeper!
    unless current_user&.shopkeeper?
      redirect_to root_path, alert: "Access denied."
    end
  end
end

app/helpers/shopkeepers/dashboard_helper.rb
module Shopkeepers::DashboardHelper
end

app/views/shopkeepers/_shopkeeper_navbar.erb
<nav class="navbar-default navbar navbar-expand-lg">
    <a id="nav-toggle" href="#">
        <i class="fe fe-menu"></i>
    </a>
    <!--Navbar nav -->
    <div class="ms-auto d-flex">
        <a href="#" class="form-check form-switch theme-switch btn btn-light btn-icon rounded-circle ">
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
            <label class="form-check-label" for="flexSwitchCheckDefault"></label>

                   </a>
    <ul class="navbar-nav navbar-right-wrap ms-2 d-flex nav-top-wrap">
        <li class="dropdown stopevent">
            <a class="btn btn-light btn-icon rounded-circle indicator indicator-primary text-muted" href="#" role="button" id="dropdownNotification" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fe fe-bell"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-lg" aria-labelledby="dropdownNotification">
                <div>
                    <div class="border-bottom px-3 pb-3 d-flex justify-content-between align-items-center">
                        <span class="h4 mb-0">Notifications</span>
                        <a href="# " class="text-muted">
                            <span class="align-middle">
                                    <i class="fe fe-settings me-1"></i>
                                </span>
                        </a>
                    </div>
                    <!-- List group -->
                    <ul class="list-group list-group-flush" data-simplebar style="max-height: 300px;">
                        <li class="list-group-item bg-light">
                            <div class="row">
                                <div class="col">
                                    <a class="text-body" href="#">
                                    <div class="d-flex">
                                        <img
                                            src="/assets/avatar-1.jpg"
                                            alt=""
                                            class="avatar-md rounded-circle"
                                        >
                                        <div class="ms-3">
                                            <h5 class="fw-bold mb-1">Kristin Watson:</h5>
                                            <p class="mb-3">
                                                Krisitn Watsan like your comment on course
                                                Javascript Introduction!
                                            </p>
                                            <span class="fs-6 text-muted">
                                                <span
                                                    ><span
                                                        class="fe fe-thumbs-up text-success me-1"
                                                    ></span
                                                    >2 hours ago,</span
                                                >
                                                <span class="ms-1">2:19 PM</span>
                                            </span>
                                        </div>
                                    </div>
                                    </a>
                                </div>
                                <div class="col-auto text-center me-2">
                                    <a
                                        href="#"
                                        class="badge-dot bg-info"
                                        data-bs-toggle="tooltip"
                                        data-bs-placement="top"

                                        title="Mark as read"
                                    >
                                    </a>
                                    <div>
                                        <a
                                            href="#"
                                            class="bg-transparent"
                                            data-bs-toggle="tooltip"
                                            data-bs-placement="top"

                                            title="Remove"
                                        >
                                            <i class="fe fe-x text-muted"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="border-top px-3 pt-3 pb-0">
                        <a href="../../pages/notification-history.html" class="text-link fw-semibold">
                                See all Notifications
                            </a>
                    </div>
                </div>
            </div>
        </li>
        <!-- List -->
        <% if user_signed_in? %>
        <li class="dropdown ms-2">
            <a class="rounded-circle" href="#" role="button" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="avatar avatar-md avatar-indicators avatar-online">
                    <img alt="avatar" src="/assets/avatar-1" class="rounded-circle" >
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownUser">
                <div class="dropdown-item">
                    <div class="d-flex">
                        <div class="avatar avatar-md avatar-indicators avatar-online">
                            <img alt="avatar" src="/assets/avatar-1.jpg" class="rounded-circle" >
                        </div>
                        <div class="ms-3 lh-1">
                            <h5 class="mb-1"><%= current_user.first_name %> <%= current_user.last_name %></h5>
                            <p class="mb-0 text-muted"><%= current_user.email %></p>
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <ul class="list-unstyled">
                    <li>
                      <% if current_user.shopkeeper? %>
                        <a class="dropdown-item" href="<%= shopkeepers_dashboard_path %>">
                          <i class="nav-icon fe fe-home me-2"></i>Dashboard
                        </a>
                      <% elsif current_user.user? %>
                        <a class="dropdown-item" href="<%= users_dashboard_path %>">
                          <i class="nav-icon fe fe-home me-2"></i>Dashboard
                        </a>
                      <% end %>
                    </li>
                    <li class="dropdown-submenu dropstart-lg">
                        <a class="dropdown-item dropdown-list-group-item dropdown-toggle" href="#">
                            <i class="fe fe-circle me-2"></i> Status
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-success me-2"></span> Online
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-secondary me-2"></span> Offline
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-warning me-2"></span> Away
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-danger me-2"></span> Busy
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-item" href="<%= edit_user_registration_path %>">
                            <i class="fe fe-user me-2"></i> Profile
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="../../pages/student-subscriptions.html">
                            <i class="fe fe-star me-2"></i> Subscription
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="fe fe-settings me-2"></i> Settings
                        </a>
                    </li>
                </ul>
                <div class="dropdown-divider"></div>
                <ul class="list-unstyled">
                    <li>
                      <%= button_to destroy_user_session_path, method: :delete, class: "dropdown-item d-inline" do %>
                        <i class="fe fe-power me-2"></i>Sign Out
                      <% end %>
                    </li>
                </ul>
            </div>
        </li>
        <% else %>
            <div class="order-lg-3">
                <div class="d-flex align-items-center">
                    <a href="<%= new_user_session_path %>" class="btn btn-outline-primary ms-2">Sign in</a>
                    <a href="<%= new_user_registration_path %>" class="btn btn-primary ms-1 d-none d-lg-block">Sign up</a>
                    <!-- Button -->
                    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="icon-bar top-bar mt-0"></span>
                        <span class="icon-bar middle-bar"></span>
                        <span class="icon-bar bottom-bar"></span>
                    </button>
                </div>
            </div>
        <% end %>
    </ul>
    </div>
</nav>

app/views/shopkeepers/_shopkeeper_shop_show_navbar.html.erb
<nav class="navbar-default navbar navbar-expand-lg">
    <a id="nav-toggle" href="#">
        <i class="fe fe-menu"></i>
    </a>
    <div class="ms-lg-3 d-none d-md-none d-lg-block">
        <!-- Form -->
        <% unless params[:action] == "new" || params[:action] == "create"%>
            <%= form_with(url: search_product_shopkeeper_shop_path, method: :get, local: true, html: { class: "d-flex align-items-center" }) do %>
                <span class="position-absolute ps-3 search-icon">
                        <i class="fe fe-search"></i>
                    </span>
                <%= text_field_tag :search, params[:search], class: "form-control ps-6", placeholder: "Search Model to add in shop" %>
              <%= submit_tag "", style:"display: none;" %>
            <% end %>
        <% end %>
    </div>
    <!--Navbar nav -->
    <div class="ms-auto d-flex">
        <a href="#" class="form-check form-switch theme-switch btn btn-light btn-icon rounded-circle ">
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
            <label class="form-check-label" for="flexSwitchCheckDefault"></label>

                   </a>
    <ul class="navbar-nav navbar-right-wrap ms-2 d-flex nav-top-wrap">
        <li class="dropdown stopevent">
            <a class="btn btn-light btn-icon rounded-circle indicator indicator-primary text-muted" href="#" role="button" id="dropdownNotification" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fe fe-bell"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-lg" aria-labelledby="dropdownNotification">
                <div>
                    <div class="border-bottom px-3 pb-3 d-flex justify-content-between align-items-center">
                        <span class="h4 mb-0">Notifications</span>
                        <a href="# " class="text-muted">
                            <span class="align-middle">
                                    <i class="fe fe-settings me-1"></i>
                                </span>
                        </a>
                    </div>
                    <!-- List group -->
                    <ul class="list-group list-group-flush" data-simplebar style="max-height: 300px;">
                        <li class="list-group-item bg-light">
                            <div class="row">
                                <div class="col">
                                    <a class="text-body" href="#">
                                    <div class="d-flex">
                                        <img
                                            src="/assets/avatar-1.jpg"
                                            alt=""
                                            class="avatar-md rounded-circle"
                                        >
                                        <div class="ms-3">
                                            <h5 class="fw-bold mb-1">Kristin Watson:</h5>
                                            <p class="mb-3">
                                                Krisitn Watsan like your comment on course
                                                Javascript Introduction!
                                            </p>
                                            <span class="fs-6 text-muted">
                                                <span
                                                    ><span
                                                        class="fe fe-thumbs-up text-success me-1"
                                                    ></span
                                                    >2 hours ago,</span
                                                >
                                                <span class="ms-1">2:19 PM</span>
                                            </span>
                                        </div>
                                    </div>
                                    </a>
                                </div>
                                <div class="col-auto text-center me-2">
                                    <a
                                        href="#"
                                        class="badge-dot bg-info"
                                        data-bs-toggle="tooltip"
                                        data-bs-placement="top"

                                        title="Mark as read"
                                    >
                                    </a>
                                    <div>
                                        <a
                                            href="#"
                                            class="bg-transparent"
                                            data-bs-toggle="tooltip"
                                            data-bs-placement="top"

                                            title="Remove"
                                        >
                                            <i class="fe fe-x text-muted"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <div class="border-top px-3 pt-3 pb-0">
                        <a href="../../pages/notification-history.html" class="text-link fw-semibold">
                                See all Notifications
                            </a>
                    </div>
                </div>
            </div>
        </li>
        <!-- List -->
        <% if user_signed_in? %>
        <li class="dropdown ms-2">
            <a class="rounded-circle" href="#" role="button" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="avatar avatar-md avatar-indicators avatar-online">
                    <img alt="avatar" src="/assets/avatar-1" class="rounded-circle" >
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownUser">
                <div class="dropdown-item">
                    <div class="d-flex">
                        <div class="avatar avatar-md avatar-indicators avatar-online">
                            <img alt="avatar" src="/assets/avatar-1.jpg" class="rounded-circle" >
                        </div>
                        <div class="ms-3 lh-1">
                            <h5 class="mb-1"><%= current_user.first_name %> <%= current_user.last_name %></h5>
                            <p class="mb-0 text-muted"><%= current_user.email %></p>
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <ul class="list-unstyled">
                    <li>
                      <% if current_user.shopkeeper? %>
                        <a class="dropdown-item" href="<%= shopkeepers_dashboard_path %>">
                          <i class="nav-icon fe fe-home me-2"></i>Dashboard
                        </a>
                      <% elsif current_user.user? %>
                        <a class="dropdown-item" href="<%= users_dashboard_path %>">
                          <i class="nav-icon fe fe-home me-2"></i>Dashboard
                        </a>
                      <% end %>
                    </li>
                    <li class="dropdown-submenu dropstart-lg">
                        <a class="dropdown-item dropdown-list-group-item dropdown-toggle" href="#">
                            <i class="fe fe-circle me-2"></i> Status
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-success me-2"></span> Online
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-secondary me-2"></span> Offline
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-warning me-2"></span> Away
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                    <span class="badge-dot bg-danger me-2"></span> Busy
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-item" href="<%= edit_user_registration_path %>">
                            <i class="fe fe-user me-2"></i> Profile
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="../../pages/student-subscriptions.html">
                            <i class="fe fe-star me-2"></i> Subscription
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            <i class="fe fe-settings me-2"></i> Settings
                        </a>
                    </li>
                </ul>
                <div class="dropdown-divider"></div>
                <ul class="list-unstyled">
                    <li>
                      <%= button_to destroy_user_session_path, method: :delete, class: "dropdown-item d-inline" do %>
                        <i class="fe fe-power me-2"></i>Sign Out
                      <% end %>
                    </li>
                </ul>
            </div>
        </li>
        <% else %>
            <div class="order-lg-3">
                <div class="d-flex align-items-center">
                    <a href="<%= new_user_session_path %>" class="btn btn-outline-primary ms-2">Sign in</a>
                    <a href="<%= new_user_registration_path %>" class="btn btn-primary ms-1 d-none d-lg-block">Sign up</a>
                    <!-- Button -->
                    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="icon-bar top-bar mt-0"></span>
                        <span class="icon-bar middle-bar"></span>
                        <span class="icon-bar bottom-bar"></span>
                    </button>
                </div>
            </div>
        <% end %>
    </ul>
    </div>
</nav>

app/views/shopkeepers/_shopkeeper_sidebar.html.erb
<nav class="navbar-vertical navbar">
    <div class="vh-100" data-simplebar>
         <!-- Brand logo -->
         <a class="navbar-brand" href="<%= root_path %>" target="_blank">
           <img src="/assets/mobilo.png" alt="Mobilo Logo">
         </a>
         <!-- Navbar nav -->
         <ul class="navbar-nav flex-column" id="sideNavbar">
             <li class="nav-item">
               <a class="nav-link" href="<%= shopkeepers_dashboard_path %>"
                  aria-expanded="false" aria-controls="navDashboard">
                 <i class="nav-icon fe fe-home me-2"></i> Dashboard
               </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link  collapsed " href="#"
                     data-bs-toggle="collapse" data-bs-target="#navCourses" aria-expanded="false"
                     aria-controls="navCourses">
                     <i class="nav-icon fe fe-book me-2"></i> Shop Management
                 </a>
                 <div id="navCourses" class="collapse "
                     data-bs-parent="#sideNavbar">
                     <ul class="nav flex-column">
                        <% if current_user.shopkeeper? %>
                          <li class="nav-item">
                            <a class="nav-link" href="<%= new_shopkeeper_shop_path %>">New Shop</a>
                          </li>
                        <% end %>
                     </ul>
                 </div>
             </li>
             <li class="nav-item">
               <a class="nav-link  collapsed " href="#"
                   data-bs-toggle="collapse" data-bs-target="#techArticles" aria-expanded="false"
                   aria-controls="techArticles">
                   <i class="nav-icon fe fe-trending-up me-2"></i> Trendings
               </a>
               <div id="techArticles" class="collapse "
                   data-bs-parent="#sideNavbar">
                   <ul class="nav flex-column">
                      <li class="nav-item">
                        <a class="nav-link" href="<%= article_categories_path %>" target="_blank"aria-expanded="false" aria-controls="navDashboard">
                          <i class="nav-icon fa fa-cogs me-2"></i> Tech Categories
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="<%= articles_path %>" target="_blank"aria-expanded="false" aria-controls="navDashboard">
                          <i class="nav-icon fe fe-file-text me-2"></i> All Tech Articles
                        </a>
                      </li>
                   </ul>
               </div>
             </li>
             <!-- Nav item -->
             <li class="nav-item">
                 <a class="nav-link  collapsed " href="#"
                     data-bs-toggle="collapse" data-bs-target="#navAuthentication" aria-expanded="false"
                     aria-controls="navAuthentication">
                     <i class="nav-icon fe fe-lock me-2"></i> Authentication
                 </a>
                 <div id="navAuthentication" class="collapse "
                     data-bs-parent="#sideNavbar">
                     <ul class="nav flex-column">
                         <li class="nav-item">
                             <a class="nav-link "
                                 href="../../pages/forget-password.html">
                                 Forget Password
                             </a>
                         </li>
                         <li class="nav-item">
                             <a class="nav-link  "
                                 href="../../pages/dashboard/notification-history.html">
                                 Notifications
                             </a>
                         </li>
                     </ul>
                 </div>
             </li>
         </ul>
    </div>
</nav>